name: Deploy
on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: What's the GITHUB_REF
        - run: echo "${GITHUB_REF}"
      - name: What's the Tag
        - run: echo "${GITHUB_REF#refs/tags/}"